# Generated by Django 5.2.1 on 2025-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
