# Generated by Django 5.2.1 on 2025-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom_app', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='dom_app.profile'),
        ),
    ]
