# Generated by Django 5.2.1 on 2025-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom_app', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
